AllCops:
  NewCops: enable

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 30

Metrics/AbcSize:
  Max: 30

Style/GlobalVars:
  Enabled: false

Style/WordArray:
  MinSize: 10

Style/ClassVars:
  Enabled: false

Metrics/BlockLength:
  Max: 50

Metrics/CyclomaticComplexity:
  Max: 20

Metrics/ModuleLength:
  Max: 120

